##################
# @file makefile
# @author Adam T Koehler, PhD
# @date October 10, 2023
# @brief Basic makefile to alter script permissions and execute it
##################

runtests:
	chmod u+x executetests.sh
	./executetests.sh
